In [66]:
# Clears all variable values previously set
# from IPython import get_ipython
# get_ipython().magic('reset -sf')

In [67]:
# Provides ways to work with large multidimensional arrays
import numpy as np 
# Allows for further data manipulation and analysis
import pandas as pd

# In Anaconda -> Environments -> Not Installed -> pandas-datareader -> Apply
from pandas_datareader import data as web # Reads stock data 
import matplotlib.pyplot as plt # Plotting
import matplotlib.dates as mdates # Styling dates
%matplotlib inline

import warnings
warnings.simplefilter("ignore")

## Constants

In [68]:
# Define path to files
# For MacOS
# PATH = "/Users/derekbanas/Documents/Tutorials/Python for Finance/"
# For Windows
PATH = "./file"

In [69]:
# Make an Numpy array
l1 = [1,2,3,4,5]
npa1 = np.array(l1)
npa1


array([1, 2, 3, 4, 5])

## Numpy Crash Course

NumPy is an amazing scientific computing library that is used by numerous other Python Data Science libraries. It contains many mathematical, array and string functions that are extremely useful. Along with all the basic math functions you'll also find them for Linear Algebra, Statistics, Simulation, etc.

NumPy utilizes vector (1D Arrays) and matrice arrays (2D Arrays).

## Create Array in Range

In [70]:
# Creates array from 0 to 4
npa2 = np.arange(0,5)
npa2

array([0, 1, 2, 3, 4])

In [71]:
# Define a step
npa3 = np.arange(0,10,2)
npa3

array([0, 2, 4, 6, 8])

## Matrices

In [72]:
# Create a 4 row matrix with 3 columns with all having a value of 1
mat1 = np.ones((4,3))
mat1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
# Create a 4 row matrix with 3 columns with all having a value of 0
mat2 = np.zeros((4,3))
mat2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Random Matrices

In [74]:
# Random values between 0 and 50 as a matrix with 4 rows & 3 columns
mat3 = np.random.randint(0,50,(4,3))
mat3

array([[42, 37, 21],
       [25, 22, 29],
       [ 2, 36, 39],
       [12, 34,  1]])

## Generate Defined Number of Values in Range

In [75]:
# Generate 10 equally distanced values between 1 and 10
mat4 = np.linspace(1,10,10)
mat4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Reshape Arrays

In [76]:
# Create array with 12 values
mat6 = np.random.randint(0,50,12)
mat6

array([ 1, 39, 37, 32, 46, 29, 46, 19, 13,  6, 11, 44])

In [77]:
# Reshape to a 3 row 4 column array
mat6 = mat6.reshape(3,4)
mat6

array([[ 1, 39, 37, 32],
       [46, 29, 46, 19],
       [13,  6, 11, 44]])

In [78]:
# Reshape into a 3D array with 3 blocks, 2 rows, 2 columns
mat7 = mat6.reshape(3,2,2)
mat7

array([[[ 1, 39],
        [37, 32]],

       [[46, 29],
        [46, 19]],

       [[13,  6],
        [11, 44]]])

In [79]:
# Reshape into a 3D array with 2 blocks, 3 rows, 2 columns
mat8 = mat6.reshape(2,3,2)
mat8

array([[[ 1, 39],
        [37, 32],
        [46, 29]],

       [[46, 19],
        [13,  6],
        [11, 44]]])

In [80]:
# Get the value in the 2nd block, 3rd row and 1st column
mat8[1,2,0]

11

## Filter Array

In [81]:
# Provide a boolean array where values are above 20
print(mat6)
mat6 > 20

[[ 1 39 37 32]
 [46 29 46 19]
 [13  6 11 44]]


array([[False,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False,  True]])

In [82]:
# Return an array with just values over 20
mat6[mat6>20]

array([39, 37, 32, 46, 29, 46, 44])

## Statistics Operations

In [83]:
# Generate 50 random values between 0 and 100
mat5 = np.random.randint(0,100,50)
mat5

print("Mean :", mat5.mean())
print("Standard Deviation :", mat5.std())
print("Variance :", mat5.var())
print("Min :", mat5.min())
print("Max :", mat5.max())

Mean : 44.58
Standard Deviation : 26.719348794459794
Variance : 713.9236
Min : 0
Max : 94


## The Seed Function

In [84]:
# Used when you want to replicate randomization
np.random.seed(500)
mat9 = np.random.randint(0,50,10)
mat9

array([26,  1, 17, 14, 31,  8,  7, 13, 45, 17])

In [85]:
# Everything goes back to random on the next call
mat10 = np.random.randint(0,50,10)
mat10

array([17, 21, 41, 34, 42, 18, 19, 13, 38, 40])

# Pandas

Pandas provides numerous tools to work with tabular data like you'd find in spreadsheets or databases. It is widely used for data preparation, cleaning, and analysis. It can work with a wide variety of data and provides many visualization options. It is built on top of NumPy.

## Read Data from a CSV

In [86]:
def get_df_from_csv(ticker):
    try:
        df = pd.read_csv(PATH + ticker + '.csv', index_col='Date', 
                         parse_dates=True)
    except FileNotFoundError:
        pass
        # print("File Doesn't Exist")
    else:
        return df

In [87]:
msft_df = get_df_from_csv("MSFT")
msft_df

## Read Data from Excel

In [88]:
def get_df_from_excel(file):
    try:
        df = pd.read_excel(file)
    except FileNotFoundError:
        pass
        print("File Doesn't Exist")
    else:
        return df

In [89]:
# You may have to run this in the Qt Console : pip install openpyxl
file = PATH + "Wilshire-5000-Stocks.xlsx"
w_stocks = get_df_from_excel(file)
w_stocks

File Doesn't Exist


## Read Data from HTML

In [90]:
g_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_current_United_States_governors")
g_data

[                                                    0
 0             This article is part of a series on the
 1              State governments of the United States
 2            State constitution Comparison Statehouse
 3                                           Executive
 4   State executives Governor (List) Other common ...
 5                                         Legislative
 6   State representatives (Alabama to Missouri, Mo...
 7                                           Judiciary
 8                     State supreme court State court
 9                                       Local offices
 10                                  District attorney
 11              Politics portal  United States portal
 12                                                vte,
                     State  Image             Governor[6]  Party[6]  \
 0          Alabama (list)    NaN                Kay Ivey       NaN   
 1           Alaska (list)    NaN           Mike Dunleavy       NaN   
 2          Ariz

In [91]:
# We can define that we want the 2nd table on the page
g_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_current_United_States_governors")[1]
g_data

State  Image             Governor[6]  Party[6]  \
0          Alabama (list)    NaN                Kay Ivey       NaN   
1           Alaska (list)    NaN           Mike Dunleavy       NaN   
2          Arizona (list)    NaN             Katie Hobbs       NaN   
3         Arkansas (list)    NaN  Sarah Huckabee Sanders       NaN   
4       California (list)    NaN            Gavin Newsom       NaN   
5         Colorado (list)    NaN             Jared Polis       NaN   
6      Connecticut (list)    NaN              Ned Lamont       NaN   
7         Delaware (list)    NaN             John Carney       NaN   
8          Florida (list)    NaN            Ron DeSantis       NaN   
9          Georgia (list)    NaN              Brian Kemp       NaN   
10          Hawaii (list)    NaN              Josh Green       NaN   
11           Idaho (list)    NaN             Brad Little       NaN   
12        Illinois (list)    NaN          J. B. Pritzker       NaN   
13         Indiana (list)    NaN            Eric Holcomb       NaN   
14            Iowa (list)    NaN            Kim Reynolds       NaN   
15          Kansas (list)    NaN             Laura Kelly       NaN   
16        Kentucky (list)    NaN            Andy Beshear       NaN   
17       Louisiana (list)    NaN             Jeff Landry       NaN   
18           Maine (list)    NaN             Janet Mills       NaN   
19        Maryland (list)    NaN               Wes Moore       NaN   
20   Massachusetts (list)    NaN            Maura Healey       NaN   
21        Michigan (list)    NaN        Gretchen Whitmer       NaN   
22       Minnesota (list)    NaN                Tim Walz       NaN   
23     Mississippi (list)    NaN             Tate Reeves       NaN   
24        Missouri (list)    NaN             Mike Parson       NaN   
25         Montana (list)    NaN          Greg Gianforte       NaN   
26        Nebraska (list)    NaN              Jim Pillen       NaN   
27          Nevada (list)    NaN            Joe Lombardo       NaN   
28   New Hampshire (list)    NaN            Chris Sununu       NaN   
29      New Jersey (list)    NaN             Phil Murphy       NaN   
30      New Mexico (list)    NaN  Michelle Lujan Grisham       NaN   
31        New York (list)    NaN            Kathy Hochul       NaN   
32  North Carolina (list)    NaN              Roy Cooper       NaN   
33    North Dakota (list)    NaN             Doug Burgum       NaN   
34            Ohio (list)    NaN             Mike DeWine       NaN   
35        Oklahoma (list)    NaN             Kevin Stitt       NaN   
36          Oregon (list)    NaN              Tina Kotek       NaN   
37    Pennsylvania (list)    NaN            Josh Shapiro       NaN   
38    Rhode Island (list)    NaN               Dan McKee       NaN   
39  South Carolina (list)    NaN          Henry McMaster       NaN   
40    South Dakota (list)    NaN             Kristi Noem       NaN   
41       Tennessee (list)    NaN                Bill Lee       NaN   
42           Texas (list)    NaN             Greg Abbott       NaN   
43            Utah (list)    NaN             Spencer Cox       NaN   
44         Vermont (list)    NaN              Phil Scott       NaN   
45        Virginia (list)    NaN          Glenn Youngkin       NaN   
46      Washington (list)    NaN              Jay Inslee       NaN   
47   West Virginia (list)    NaN             Jim Justice       NaN   
48       Wisconsin (list)    NaN              Tony Evers       NaN   
49         Wyoming (list)    NaN             Mark Gordon       NaN   

                         Party[6].1                         Born  \
0                        Republican    October 15, 1944 (age 80)   
1                        Republican         May 5, 1961 (age 63)   
2                        Democratic   December 28, 1969 (age 54)   
3                        Republican     August 13, 1982 (age 42)   
4                        Democratic    October 10, 1967 (age 57)   
5                        Democratic      

## US Demographics

In [92]:
# You can also search for phrases in the table
d_data = pd.read_html("https://en.wikipedia.org/wiki/Demographics_of_the_United_States", 
                      match="Average population")[0]
d_data

Unnamed: 0  Average population Live births[103]   Deaths  \
0             1935           127250000          2377000  1392752   
1             1936           128053000          2355000  1479228   
2             1937           128825000          2413000  1450427   
3             1938           129825000          2496000  1381391   
4             1939           130880000          2466000  1387897   
..             ...                 ...              ...      ...   
84            2019           328329953          3747540  2854858   
85  2020[110][111]           331511512          3613647  3383729   
86  2021[112][113]           332031554          3664292  3464231   
87  2022[114][115]           333287557   3,667,758[116]  3279857   
88      2023p[117]           334914865          3596017  3087366   

    Natural change  Crude birth rate (per 1,000)  \
0           984248                          18.7   
1           875772                          18.4   
2           962573                          18.7   
3          1114609                          19.2   
4          1078103                          18.8   
..             ...                           ...   
84          892682                          11.4   
85          229918                          10.9   
86          200061                          11.0   
87          387901                          11.0   
88          507932                          10.7   

    Crude death rate (per 1,000)[104]  Natural change (per 1,000)  \
0                                10.9                         7.7   
1                                11.5                         6.8   
2                                11.2                         7.5   
3                                10.6                         8.6   
4                                10.6                         8.2   
..                                ...                         ...   
84                                8.7                         2.7   
85                               10.3                         0.6   
86                               10.4                         0.5   
87                                9.8                         1.2   
88                                9.2                         1.5   

    Crude migration change (per 1,000)  Total fertility rate[fn 1][105]  
0                                  NaN                            2.190  
1                                 -0.5                            2.150  
2                                 -1.5                            2.170  
3                                 -0.9                            2.220  
4                                 -0.1                            2.170  
..                                 ...                              ...  
84                                 1.9                            1.706  
85                                 9.1                            1.641  
86                                 1.1                            1.664  
87                                 2.6                            1.656  
88                                 3.3                            1.617  

[89 rows x 10 columns]

## Replace Spaces in Column Names

In [93]:
d_data.columns = [x.replace(' ', '_') for x in d_data.columns]
d_data

Unnamed:_0  Average_population Live_births[103]   Deaths  \
0             1935           127250000          2377000  1392752   
1             1936           128053000          2355000  1479228   
2             1937           128825000          2413000  1450427   
3             1938           129825000          2496000  1381391   
4             1939           130880000          2466000  1387897   
..             ...                 ...              ...      ...   
84            2019           328329953          3747540  2854858   
85  2020[110][111]           331511512          3613647  3383729   
86  2021[112][113]           332031554          3664292  3464231   
87  2022[114][115]           333287557   3,667,758[116]  3279857   
88      2023p[117]           334914865          3596017  3087366   

    Natural_change  Crude_birth_rate_(per_1,000)  \
0           984248                          18.7   
1           875772                          18.4   
2           962573                          18.7   
3          1114609                          19.2   
4          1078103                          18.8   
..             ...                           ...   
84          892682                          11.4   
85          229918                          10.9   
86          200061                          11.0   
87          387901                          11.0   
88          507932                          10.7   

    Crude_death_rate_(per_1,000)[104]  Natural_change_(per_1,000)  \
0                                10.9                         7.7   
1                                11.5                         6.8   
2                                11.2                         7.5   
3                                10.6                         8.6   
4                                10.6                         8.2   
..                                ...                         ...   
84                                8.7                         2.7   
85                               10.3                         0.6   
86                               10.4                         0.5   
87                                9.8                         1.2   
88                                9.2                         1.5   

    Crude_migration_change_(per_1,000)  Total_fertility_rate[fn_1][105]  
0                                  NaN                            2.190  
1                                 -0.5                            2.150  
2                                 -1.5                            2.170  
3                                 -0.9                            2.220  
4                                 -0.1                            2.170  
..                                 ...                              ...  
84                                 1.9                            1.706  
85                                 9.1                            1.641  
86                                 1.1                            1.664  
87                                 2.6                            1.656  
88                                 3.3                            1.617  

[89 rows x 10 columns]

## Remove Characters in Columns

In [94]:
# Remove parentheses and whats inside them
d_data.columns = d_data.columns.str.replace(r"\(.*\)","")
# Remove brackets and whats inside them
d_data.columns = d_data.columns.str.replace(r"\[.*\]","")
d_data

Unnamed:_0  Average_population Live_births[103]   Deaths  \
0             1935           127250000          2377000  1392752   
1             1936           128053000          2355000  1479228   
2             1937           128825000          2413000  1450427   
3             1938           129825000          2496000  1381391   
4             1939           130880000          2466000  1387897   
..             ...                 ...              ...      ...   
84            2019           328329953          3747540  2854858   
85  2020[110][111]           331511512          3613647  3383729   
86  2021[112][113]           332031554          3664292  3464231   
87  2022[114][115]           333287557   3,667,758[116]  3279857   
88      2023p[117]           334914865          3596017  3087366   

    Natural_change  Crude_birth_rate_(per_1,000)  \
0           984248                          18.7   
1           875772                          18.4   
2           962573                          18.7   
3          1114609                          19.2   
4          1078103                          18.8   
..             ...                           ...   
84          892682                          11.4   
85          229918                          10.9   
86          200061                          11.0   
87          387901                          11.0   
88          507932                          10.7   

    Crude_death_rate_(per_1,000)[104]  Natural_change_(per_1,000)  \
0                                10.9                         7.7   
1                                11.5                         6.8   
2                                11.2                         7.5   
3                                10.6                         8.6   
4                                10.6                         8.2   
..                                ...                         ...   
84                                8.7                         2.7   
85                               10.3                         0.6   
86                               10.4                         0.5   
87                                9.8                         1.2   
88                                9.2                         1.5   

    Crude_migration_change_(per_1,000)  Total_fertility_rate[fn_1][105]  
0                                  NaN                            2.190  
1                                 -0.5                            2.150  
2                                 -1.5                            2.170  
3                                 -0.9                            2.220  
4                                 -0.1                            2.170  
..                                 ...                              ...  
84                                 1.9                            1.706  
85                                 9.1                            1.641  
86                                 1.1                            1.664  
87                                 2.6                            1.656  
88                                 3.3                            1.617  

[89 rows x 10 columns]

## Rename Columns

In [95]:
# You could add additional with commas between {}
d_data = d_data.rename(columns={'Unnamed:_0': 'Year'})
d_data

Year  Average_population Live_births[103]   Deaths  \
0             1935           127250000          2377000  1392752   
1             1936           128053000          2355000  1479228   
2             1937           128825000          2413000  1450427   
3             1938           129825000          2496000  1381391   
4             1939           130880000          2466000  1387897   
..             ...                 ...              ...      ...   
84            2019           328329953          3747540  2854858   
85  2020[110][111]           331511512          3613647  3383729   
86  2021[112][113]           332031554          3664292  3464231   
87  2022[114][115]           333287557   3,667,758[116]  3279857   
88      2023p[117]           334914865          3596017  3087366   

    Natural_change  Crude_birth_rate_(per_1,000)  \
0           984248                          18.7   
1           875772                          18.4   
2           962573                          18.7   
3          1114609                          19.2   
4          1078103                          18.8   
..             ...                           ...   
84          892682                          11.4   
85          229918                          10.9   
86          200061                          11.0   
87          387901                          11.0   
88          507932                          10.7   

    Crude_death_rate_(per_1,000)[104]  Natural_change_(per_1,000)  \
0                                10.9                         7.7   
1                                11.5                         6.8   
2                                11.2                         7.5   
3                                10.6                         8.6   
4                                10.6                         8.2   
..                                ...                         ...   
84                                8.7                         2.7   
85                               10.3                         0.6   
86                               10.4                         0.5   
87                                9.8                         1.2   
88                                9.2                         1.5   

    Crude_migration_change_(per_1,000)  Total_fertility_rate[fn_1][105]  
0                                  NaN                            2.190  
1                                 -0.5                            2.150  
2                                 -1.5                            2.170  
3                                 -0.9                            2.220  
4                                 -0.1                            2.170  
..                                 ...                              ...  
84                                 1.9                            1.706  
85                                 9.1                            1.641  
86                                 1.1                            1.664  
87                                 2.6                            1.656  
88                                 3.3                            1.617  

[89 rows x 10 columns]

## Remove Characters in Columns

In [96]:
# Removes brackets and what is inside for whole column
d_data.Year = d_data.Year.str.replace(r"\[.*\]","")
d_data

Year  Average_population Live_births[103]   Deaths  \
0             1935           127250000          2377000  1392752   
1             1936           128053000          2355000  1479228   
2             1937           128825000          2413000  1450427   
3             1938           129825000          2496000  1381391   
4             1939           130880000          2466000  1387897   
..             ...                 ...              ...      ...   
84            2019           328329953          3747540  2854858   
85  2020[110][111]           331511512          3613647  3383729   
86  2021[112][113]           332031554          3664292  3464231   
87  2022[114][115]           333287557   3,667,758[116]  3279857   
88      2023p[117]           334914865          3596017  3087366   

    Natural_change  Crude_birth_rate_(per_1,000)  \
0           984248                          18.7   
1           875772                          18.4   
2           962573                          18.7   
3          1114609                          19.2   
4          1078103                          18.8   
..             ...                           ...   
84          892682                          11.4   
85          229918                          10.9   
86          200061                          11.0   
87          387901                          11.0   
88          507932                          10.7   

    Crude_death_rate_(per_1,000)[104]  Natural_change_(per_1,000)  \
0                                10.9                         7.7   
1                                11.5                         6.8   
2                                11.2                         7.5   
3                                10.6                         8.6   
4                                10.6                         8.2   
..                                ...                         ...   
84                                8.7                         2.7   
85                               10.3                         0.6   
86                               10.4                         0.5   
87                                9.8                         1.2   
88                                9.2                         1.5   

    Crude_migration_change_(per_1,000)  Total_fertility_rate[fn_1][105]  
0                                  NaN                            2.190  
1                                 -0.5                            2.150  
2                                 -1.5                            2.170  
3                                 -0.9                            2.220  
4                                 -0.1                            2.170  
..                                 ...                              ...  
84                                 1.9                            1.706  
85                                 9.1                            1.641  
86                                 1.1                            1.664  
87                                 2.6                            1.656  
88                                 3.3                            1.617  

[89 rows x 10 columns]

## Select Columns

In [97]:
d_data['Deaths']

0     1392752
1     1479228
2     1450427
3     1381391
4     1387897
       ...   
84    2854858
85    3383729
86    3464231
87    3279857
88    3087366
Name: Deaths, Length: 89, dtype: int64

## Make a Column an Index

In [98]:
d_data.set_index('Year', inplace=True)
d_data

Average_population Live_births[103]   Deaths  Natural_change  \
Year                                                                           
1935                     127250000          2377000  1392752          984248   
1936                     128053000          2355000  1479228          875772   
1937                     128825000          2413000  1450427          962573   
1938                     129825000          2496000  1381391         1114609   
1939                     130880000          2466000  1387897         1078103   
...                            ...              ...      ...             ...   
2019                     328329953          3747540  2854858          892682   
2020[110][111]           331511512          3613647  3383729          229918   
2021[112][113]           332031554          3664292  3464231          200061   
2022[114][115]           333287557   3,667,758[116]  3279857          387901   
2023p[117]               334914865          3596017  3087366          507932   

                Crude_birth_rate_(per_1,000)  \
Year                                           
1935                                    18.7   
1936                                    18.4   
1937                                    18.7   
1938                                    19.2   
1939                                    18.8   
...                                      ...   
2019                                    11.4   
2020[110][111]                          10.9   
2021[112][113]                          11.0   
2022[114][115]                          11.0   
2023p[117]                              10.7   

                Crude_death_rate_(per_1,000)[104]  Natural_change_(per_1,000)  \
Year                                                                            
1935                                         10.9                         7.7   
1936                                         11.5                         6.8   
1937                                         11.2                         7.5   
1938                                         10.6                         8.6   
1939                                         10.6                         8.2   
...                                           ...                         ...   
2019                                          8.7                         2.7   
2020[110][111]                               10.3                         0.6   
2021[112][113]                               10.4                         0.5   
2022[114][115]                                9.8                         1.2   
2023p[117]                                    9.2                         1.5   

                Crude_migration_change_(per_1,000)  \
Year                                                 
1935                                           NaN   
1936                                          -0.5   
1937                                          -1.5   
1938                                          -0.9   
1939                                          -0.1   
...                                            ...   
2019                                           1.9   
2020[110][111]                                 9.1   
2021[112][113]                                 1.1   
2022[114][115]                                 2.6   
2023p[117]                                     3.3   

                Total_fertility_rate[fn_1][105]  
Year                                             
1935                                      2.190  
1936                                      2.150  
1937                                      2.170  
1938                                      2.220  
1939                                      2.170  
...                                         ...  
2019                                      1.706  
2020[110][111]                            1.641  
2021[112][113]                            1.664  
2022[114][115]                            1

## Grab Data from Multiple Columns

In [99]:
# d_data[["Live_births", "Deaths"]]

## Grab a Row

In [100]:
# d_data.loc['2020']

In [101]:
d_data.iloc[85]

Average_population                    331511512
Live_births[103]                        3613647
Deaths                                  3383729
Natural_change                           229918
Crude_birth_rate_(per_1,000)               10.9
Crude_death_rate_(per_1,000)[104]          10.3
Natural_change_(per_1,000)                  0.6
Crude_migration_change_(per_1,000)          9.1
Total_fertility_rate[fn_1][105]           1.641
Name: 2020[110][111], dtype: object

## Add a Column

In [102]:
# Create a column showing population growth for each year
# d_data['Pop_Growth'] = d_data["Live_births"] - d_data["Deaths"]
# d_data

## Delete Column

In [103]:
# d_data.drop('Pop_Growth', axis=1, inplace=True)
# d_data

## Delete a Row

In [104]:
d_data.drop('1935', axis=0, inplace=True)
d_data

Average_population Live_births[103]   Deaths  Natural_change  \
Year                                                                           
1936                     128053000          2355000  1479228          875772   
1937                     128825000          2413000  1450427          962573   
1938                     129825000          2496000  1381391         1114609   
1939                     130880000          2466000  1387897         1078103   
1940                     131930000          2559000  1417269         1142000   
...                            ...              ...      ...             ...   
2019                     328329953          3747540  2854858          892682   
2020[110][111]           331511512          3613647  3383729          229918   
2021[112][113]           332031554          3664292  3464231          200061   
2022[114][115]           333287557   3,667,758[116]  3279857          387901   
2023p[117]               334914865          3596017  3087366          507932   

                Crude_birth_rate_(per_1,000)  \
Year                                           
1936                                    18.4   
1937                                    18.7   
1938                                    19.2   
1939                                    18.8   
1940                                    19.4   
...                                      ...   
2019                                    11.4   
2020[110][111]                          10.9   
2021[112][113]                          11.0   
2022[114][115]                          11.0   
2023p[117]                              10.7   

                Crude_death_rate_(per_1,000)[104]  Natural_change_(per_1,000)  \
Year                                                                            
1936                                         11.5                         6.8   
1937                                         11.2                         7.5   
1938                                         10.6                         8.6   
1939                                         10.6                         8.2   
1940                                         10.8                         8.7   
...                                           ...                         ...   
2019                                          8.7                         2.7   
2020[110][111]                               10.3                         0.6   
2021[112][113]                               10.4                         0.5   
2022[114][115]                                9.8                         1.2   
2023p[117]                                    9.2                         1.5   

                Crude_migration_change_(per_1,000)  \
Year                                                 
1936                                          -0.5   
1937                                          -1.5   
1938                                          -0.9   
1939                                          -0.1   
1940                                          -0.7   
...                                            ...   
2019                                           1.9   
2020[110][111]                                 9.1   
2021[112][113]                                 1.1   
2022[114][115]                                 2.6   
2023p[117]                                     3.3   

                Total_fertility_rate[fn_1][105]  
Year                                             
1936                                      2.150  
1937                                      2.170  
1938                                      2.220  
1939                                      2.170  
1940                                      2.301  
...                                         ...  
2019                                      1.706  
2020[110][111]                            1.641  
2021[112][113]                            1.664  
2022[114][115]                            1

## Manipulating Data

In [105]:
c_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)")[2]
c_data

Country/Territory IMF[1][13]            World Bank[14]             \
    Country/Territory   Forecast       Year       Estimate       Year   
0               World  109529216       2024      105435540       2023   
1       United States   28781083       2024       27360935       2023   
2               China   18532633  [n 1]2024       17794782  [n 3]2023   
3             Germany    4591100       2024        4456081       2023   
4               Japan    4110452       2024        4212945       2023   
..                ...        ...        ...            ...        ...   
205          Kiribati        311       2024            279       2023   
206             Palau        308       2024            263       2023   
207  Marshall Islands        305       2024            284       2023   
208             Nauru        161       2024            154       2023   
209            Tuvalu         66       2024             62       2023   

    United Nations[15]             
              Estimate       Year  
0            100834796       2022  
1             25744100       2022  
2             17963170  [n 1]2022  
3              4076923       2022  
4              4232173       2022  
..                 ...        ...  
205                223       2022  
206                225       2022  
207                279       2022  
208                147       2022  
209                 59       2022  

[210 rows x 7 columns]

In [106]:
for col in c_data.columns:
    print(col)

('Country/Territory', 'Country/Territory')
('IMF[1][13]', 'Forecast')
('IMF[1][13]', 'Year')
('World Bank[14]', 'Estimate')
('World Bank[14]', 'Year')
('United Nations[15]', 'Estimate')
('United Nations[15]', 'Year')


In [107]:
# Delete a level of a multilevel column name
c_data.columns = c_data.columns.droplevel()
c_data


Country/Territory   Forecast       Year   Estimate       Year   Estimate  \
0               World  109529216       2024  105435540       2023  100834796   
1       United States   28781083       2024   27360935       2023   25744100   
2               China   18532633  [n 1]2024   17794782  [n 3]2023   17963170   
3             Germany    4591100       2024    4456081       2023    4076923   
4               Japan    4110452       2024    4212945       2023    4232173   
..                ...        ...        ...        ...        ...        ...   
205          Kiribati        311       2024        279       2023        223   
206             Palau        308       2024        263       2023        225   
207  Marshall Islands        305       2024        284       2023        279   
208             Nauru        161       2024        154       2023        147   
209            Tuvalu         66       2024         62       2023         59   

          Year  
0         2022  
1         2022  
2    [n 1]2022  
3         2022  
4         2022  
..         ...  
205       2022  
206       2022  
207       2022  
208       2022  
209       2022  

[210 rows x 7 columns]

In [108]:
# Keep only columns if they haven't used the same name prior
c_data = c_data.loc[:,~c_data.columns.duplicated()]
c_data

Country/Territory   Forecast       Year   Estimate
0               World  109529216       2024  105435540
1       United States   28781083       2024   27360935
2               China   18532633  [n 1]2024   17794782
3             Germany    4591100       2024    4456081
4               Japan    4110452       2024    4212945
..                ...        ...        ...        ...
205          Kiribati        311       2024        279
206             Palau        308       2024        263
207  Marshall Islands        305       2024        284
208             Nauru        161       2024        154
209            Tuvalu         66       2024         62

[210 rows x 4 columns]

In [109]:
# Delete any rows with NaN values by taking only rows that don't contain NaNs
c_data = c_data[c_data['Estimate'].notna()]
c_data


Country/Territory   Forecast       Year   Estimate
0               World  109529216       2024  105435540
1       United States   28781083       2024   27360935
2               China   18532633  [n 1]2024   17794782
3             Germany    4591100       2024    4456081
4               Japan    4110452       2024    4212945
..                ...        ...        ...        ...
205          Kiribati        311       2024        279
206             Palau        308       2024        263
207  Marshall Islands        305       2024        284
208             Nauru        161       2024        154
209            Tuvalu         66       2024         62

[210 rows x 4 columns]

In [110]:
# Remove []s and what is in them in Year column
# Removes brackets and what is inside for whole column
c_data.Year = c_data.Year.str.replace(r"\[.*\]","")
c_data

Country/Territory   Forecast       Year   Estimate
0               World  109529216       2024  105435540
1       United States   28781083       2024   27360935
2               China   18532633  [n 1]2024   17794782
3             Germany    4591100       2024    4456081
4               Japan    4110452       2024    4212945
..                ...        ...        ...        ...
205          Kiribati        311       2024        279
206             Palau        308       2024        263
207  Marshall Islands        305       2024        284
208             Nauru        161       2024        154
209            Tuvalu         66       2024         62

[210 rows x 4 columns]

In [111]:
# Rename country column
c_data.rename(columns={"Country/Territory": "Country", "Estimate": "GDP"}, 
              inplace=True)
c_data

Country   Forecast       Year        GDP
0               World  109529216       2024  105435540
1       United States   28781083       2024   27360935
2               China   18532633  [n 1]2024   17794782
3             Germany    4591100       2024    4456081
4               Japan    4110452       2024    4212945
..                ...        ...        ...        ...
205          Kiribati        311       2024        279
206             Palau        308       2024        263
207  Marshall Islands        305       2024        284
208             Nauru        161       2024        154
209            Tuvalu         66       2024         62

[210 rows x 4 columns]

In [112]:
# Remove * in Country column
c_data.Country = c_data.Country.str.replace("*","")
c_data

Country   Forecast       Year        GDP
0               World  109529216       2024  105435540
1       United States   28781083       2024   27360935
2               China   18532633  [n 1]2024   17794782
3             Germany    4591100       2024    4456081
4               Japan    4110452       2024    4212945
..                ...        ...        ...        ...
205          Kiribati        311       2024        279
206             Palau        308       2024        263
207  Marshall Islands        305       2024        284
208             Nauru        161       2024        154
209            Tuvalu         66       2024         62

[210 rows x 4 columns]

In [113]:
# Groupby allows you to group rows based on a column and perform a function
# Mean GDP by region
# c_data.groupby("Region").mean()

In [114]:
# Median GDP by region
# c_data.groupby("Region").median()

## More Ways of Messing with Data

In [115]:
# Dictionary with ice cream sales data
dict1 = {'Store': [1,2,1,2], 'Flavor': ['Choc', 'Van', 'Straw', 'Choc'], 
         'Sales': [26, 12, 18, 22]}

# Convert to Dataframe
ic_data = pd.DataFrame(dict1)

# Group data by the store number
by_store = ic_data.groupby('Store')
# Get mean sales by store
# by_store.mean()

# Get sales total just for store 1
by_store.sum().loc[1]

# You can use multiple functions of get a bunch
by_store.describe()

Sales                                              
      count  mean       std   min   25%   50%   75%   max
Store                                                    
1       2.0  22.0  5.656854  18.0  20.0  22.0  24.0  26.0
2       2.0  17.0  7.071068  12.0  14.5  17.0  19.5  22.0

## Plotly

Plotly allows you to create over 40 beautiful interactive web-based visualizations that can be displayed in Jupyter notebooks or saved to HTML files. It is widely used to plot scientific, statistical and financial data.

You can install using Anaconda under the environment tab by searching for Plotly. You'll also need Cufflinks and a few other packages that you can install by running : conda install -c conda-forge cufflinks-py in your command line or terminal. Also you can use the commands pip install plotly and pip install cufflinks. Cufflinks connects Plotly to Pandas.

In [116]:
import cufflinks as cf
import plotly.express as px
import plotly.graph_objects as go

# Make Plotly work in your Jupyter Notebook
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
# Use Plotly locally
cf.go_offline()

## Line Plot

In [117]:
# Plot the value of a dollar invested over time
# Use included Google price data to make one plot
df_stocks = px.data.stocks()
px.line(df_stocks, x='date', y='GOOG', labels={'x':'Date', 
                                               'y':'Value of Dollar'})

# Make multiple line plots
px.line(df_stocks, x='date', y=['GOOG','AAPL'], labels={'x':'Date', 
                                                        'y':'Value of Dollar'},
       title='Apple Vs. Google').show(renderer="iframe")

In [118]:
# Multiple plots
r_x1 = np.linspace(0,1,100)
r_y0 = np.random.randn(100) + 5
r_y1 = np.random.randn(100) - 5
r_y2 = np.random.randn(100)

fig = go.Figure()
# There are many line styles
fig.add_trace(go.Scatter(x=r_x1, y=r_y0, mode='lines', name='Rand 1'))
fig.add_trace(go.Scatter(x=r_x1, y=r_y1, mode='lines+markers', name='Rand 2'))
fig.add_trace(go.Scatter(x=r_x1, y=r_y2, mode='markers', name='Rand 3'))

fig.show(renderer="iframe")

## Add Details to Plot

In [119]:
aapl_df = pd.read_csv( PATH + '/AAPL.csv')
x = aapl_df['Date']
y = aapl_df['Adj Close']
aapl_df
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y))
fig.update_xaxes(
    rangeslider_visible=True, title='Zoom on Dates Using Slider')
fig.update_yaxes(title="Stock Price (USD)").show(renderer="iframe")


## More Details

In [120]:
msft_df = pd.read_csv( PATH + '/MSFT.csv')
x = msft_df['Date']
y = msft_df['Adj Close']
msft_df
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y))

# Add a range slider with buttons for dates
fig.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=10,
                     label="10D",
                     step="day",
                     stepmode="backward"),
                dict(count=1,
                     label="1M",
                     step="month",
                     stepmode="backward"),
                dict(count=6,
                     label="6M",
                     step="month",
                     stepmode="todate"),
                dict(count=1,
                     label="YTD",
                     step="year",
                     stepmode="todate"),
                dict(count=1,
                     label="1Y",
                     step="year",
                     stepmode="backward"),
                dict(label="All", step="all")
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
)
fig.update_yaxes(title="Stock Price (USD)").show(renderer="iframe")

## Candlestick Plots

In [121]:
# Candlestick charts are useful because they show the open and close in the
# wide part "Real Body" and the high and low using the Shadows or Wicks.
# They can be used to sense emotion in a stock in the near term.
x = aapl_df['Date']
close = aapl_df['Adj Close']
high = aapl_df['High']
low = aapl_df['Low']
openp = aapl_df['Open']

fig = go.Figure()

fig.add_trace(go.Candlestick(x=x, high=high, low=low, 
                             open=openp, close=close))



fig.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=10,
                     label="10D",
                     step="day",
                     stepmode="backward"),
                dict(count=1,
                     label="1M",
                     step="month",
                     stepmode="backward"),
                dict(count=6,
                     label="6M",
                     step="month",
                     stepmode="todate"),
                dict(count=1,
                     label="YTD",
                     step="year",
                     stepmode="todate"),
                dict(count=1,
                     label="1Y",
                     step="year",
                     stepmode="backward"),
                dict(label="All", step="all")
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
)
fig.update_layout(xaxis_title="Dates", yaxis_title="Stock Price (USD)", 
                  title="Apple Candlestick Chart")

# Add an annotation
fig.update_layout(annotations=[dict(x='2020-02-21', y=85, 
                                    text='Pandemic Effects Market',
                                   xanchor='right')])
# Add line defining an area
fig.update_layout(shapes=[dict(x0='2020-02-21', x1='2020-04-06', 
                                    y0=0, y1=1)])
# Add a rectangle
# fig.add_shape(type="rect",
#     x0='2020-02-21', y0=0, x1='2020-04-06', y1=145,
#     line=dict(
#         color="RoyalBlue",
#         width=2,
#     ),
#     fillcolor="LightSkyBlue",
# )

# Add a vertical rectangle with opacity
fig.add_vrect(
    x0='2020-02-21', x1='2020-04-06',
    fillcolor="LightSalmon", opacity=0.5,
    layer="below", line_width=0,
)

fig.show(renderer="iframe")

## Open-High-Low-Close (OHLC) Chart

In [122]:
# While a candlestick chart has a rectangle representing the open and close
# An OHLC chart shows all 4 data points using ticks and when the opening
# and closing prices are fall apart that shows momentum up or down
# The tick on the left is the opening price and the left is the close
fig = go.Figure()

fig.add_trace(go.Ohlc(x=x, high=high, low=low, open=openp, close=close))

fig.show(renderer="iframe")

## Multiple Plots

In [123]:
fig = go.Figure()

fig.add_trace(go.Ohlc(x=x, high=high, low=low, open=openp, close=close))

a_x = aapl_df['Date']
a_y = aapl_df['Adj Close']
fig.add_trace(go.Scatter(x=a_x, y=a_y,line=dict(color='blue', 
                                                width=1.5, dash="dot")))

fig.show(renderer="iframe")

## Scatter Plots

In [124]:
x = np.arange(0,50,2)
y = np.arange(0,50,2)

# Create a figure to which I'll add plots
fig = go.Figure()

# Markers just shows the dots
fig.add_trace(go.Scatter(x=x, y=y, mode='markers'))

fig.show(renderer="iframe")

In [125]:
# Use included Iris data set
df_iris = px.data.iris()
# Create a scatter plot by defining x, y, different color for count of provided
# column, size based on supplied column and additional data to display on hover
px.scatter(df_iris, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])

# Create a customized scatter with black marker edges with line width 2, opaque
# and colored based on width. Also show a scale on the right
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=df_iris.sepal_width, y=df_iris.sepal_length,
    mode='markers',
    marker_color=df_iris.sepal_width,
    text=df_iris.species,
    marker=dict(showscale=True)))
fig.update_traces(marker_line_width=2, marker_size=10)

# Working with a lot of data use Scattergl
fig = go.Figure(data=go.Scattergl(
    x = np.random.randn(100000),
    y = np.random.randn(100000),
    mode='markers',
    marker=dict(
        color=np.random.randn(100000),
        colorscale='Viridis',
        line_width=1)))
fig.show(renderer="iframe")

## Histogram

In [126]:
# Plot histogram based on rolling 2 dice
dice_1 = np.random.randint(1,7,5000)
dice_2 = np.random.randint(1,7,5000)
dice_sum = dice_1 + dice_2
# bins represent the number of bars to make
# Can define x label, color, title
# marginal creates another plot (violin, box, rug)
fig = px.histogram(dice_sum, nbins=11, labels={'value':'Dice Roll'},
             title='5000 Dice Roll Histogram', marginal='violin',
            color_discrete_sequence=['green'])

fig.update_layout(
    xaxis_title_text='Dice Roll',
    yaxis_title_text='Dice Sum',
    bargap=0.2, showlegend=False
).show(renderer="iframe")

# Stack histograms based on different column data
df_tips = px.data.tips()
px.histogram(df_tips, x="total_bill", color="sex").show(renderer="iframe")